---
- hosts: elk001
  remote_user: vagrant
  become: yes
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    download_folder: /opt
    java_name:
      - "epel-release" 
      - "java-1.8.0-openjdk"
      - "java-1.8.0-openjdk-devel"
    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"


  tasks:
    - name: Install Updates
      yum: update_cache=yes

    - name: Install Java
      yum:
        name: "{{ java_name }}"
        state: present


